/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software component is licensed under terms that can be found in the
 * LICENSE file in the root directory of this software component. If no LICENSE
 * file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>
#include <time.h>

// Для _gettimeofday / usleep (добавлены вручную, см. в конце файла)
#include "cmsis_os.h"  // osDelay — задержка потока RTOS в миллисекундах
#include "main.h"      // HAL_GetTick — счётчик миллисекунд с момента старта

/*
 * ============================================================================
 * ЧТО ЭТО ЗА ФАЙЛ И КАК ОН УСТРОЕН
 * ----------------------------------------------------------------------------
 * Стандартная C-библиотека (newlib / picolibc), которую использует прошивка,
 * ожидает, что на «голом» микроконтроллере (без операционной системы) ряд
 * «системных» функций написан вручную. Без них линковщик упадёт с ошибкой
 * "undefined reference to `_getpid'" и т.п.
 *
 * КЛЮЧЕВЫЕ ПОНЯТИЯ (все эти вещи встречаются ниже в коде):
 *
 * __attribute__((weak)) — «слабое» определение (weak symbol).
 *   Если в проекте есть ОБЫЧНОЕ («сильное») определение этой же функции,
 *   линковщик возьмёт его, а слабое проигнорирует. Это позволяет библиотеке
 *   дать реализацию «по умолчанию», которую можно переопределить в своём коде
 *   БЕЗ ошибки «повторное определение».
 *   Пример: _read и _write объявлены weak — чтобы выводить текст в UART,
 *   достаточно написать свою версию _write.
 *
 * extern — «эта переменная/функция определена в другом файле».
 *   __io_putchar / __io_getchar определены где-то ещё (например, в
 *   stm32f4xx_it.c). extern говорит компилятору: не создавай их здесь,
 *   просто дай мне ими пользоваться.
 *
 * char **environ / __env — список переменных окружения (environment),
 *   как переменные среды в Linux. Для прошивки он пустой:
 *   __env[1] = { 0 } означает «массив из одного элемента-пустой строки»,
 *   а указатель environ указывает на него.
 *
 * errno — глобальная переменная с кодом последней ошибки (из <errno.h>).
 *   Системные функции при неудаче возвращают -1 и записывают сюда ПРИЧИНУ,
 *   чтобы вызывающий код мог её прочитать (EINVAL, ENOMEM, ...).
 *
 * FILE / FDEV_SETUP_STREAM — стандартные потоки ввода-вывода picolibc.
 *   FDEV_SETUP_STREAM «связывает» наши __io_putchar/__io_getchar с
 *   FILE-структурой, чтобы printf("...") / scanf() работали через UART.
 *   stdin/stdout/stderr — стандартные потоки, как в любом C-приложении.
 *
 * __strong_reference — макрос picolibc: «дай функции с подчёркиванием
 *   (_read) второе имя без подчёркивания (read)». Библиотека вызывает стабы
 *   по стандартным именам, поэтому для неё нужно и то и другое имя.
 *
 * ПОЧЕМУ ЗДЕСЬ _gettimeofday и usleep:
 *   micro-ROS внутри себя вызывает usleep() и _gettimeofday() (таймауты и
 *   часы). CubeMX не создаёт эти стабы автоматически, поэтому мы добавили
 *   их вручную в конце файла. Хендлы для них: HAL_GetTick() и osDelay().
 * ============================================================================
 */

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));

char* __env[1] = {0};
char** environ = __env;

/* Functions */
// Пустая заглушка семи-хостинга (арм-отладчик). Ничего не делает.
void initialise_monitor_handles() {}

// Возвращает «PID» (номер процесса). Всегда 1, процессов у нас нет.
int _getpid(void) { return 1; }

// «Убивает» процесс по PID и сигналу. Сигналы не поддерживаем — всегда ошибка.
int _kill(int pid, int sig) {
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

// Аварийный выход из программы: вешаемся в бесконечном цикле.
void _exit(int status) {
  _kill(status, -1);
  while (1) {
  } /* Make sure we hang here */
}

// Чтение len символов через __io_getchar (переопределить для приёма по UART).
__attribute__((weak)) int _read(int file, char* ptr, int len) {
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    *ptr++ = __io_getchar();
  }

  return len;
}

// Запись len символов через __io_putchar (переопределить для вывода в UART).
// Например, чтобы printf() печатал в UART — реализуй __io_putchar.
__attribute__((weak)) int _write(int file, char* ptr, int len) {
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    __io_putchar(*ptr++);
  }
  return len;
}

// Закрытие файла. Файлов у нас нет — всегда ошибка.
int _close(int file) {
  (void)file;
  return -1;
}

// Описание файла для библиотеки: говорим «это символьное устройство»
// (терминал).
int _fstat(int file, struct stat* st) {
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

// «Этот файл — терминал?» → да. Нужно для работы printf с потоком вывода.
int _isatty(int file) {
  (void)file;
  return 1;
}

// Перемещение позиции в файле. Файлов нет — всегда 0.
int _lseek(int file, int ptr, int dir) {
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

// Открытие файла. Всегда «открыть не удалось».
int _open(char* path, int flags, ...) {
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

// Ожидание завершения дочернего процесса. Дочек нет — ошибка.
int _wait(int* status) {
  (void)status;
  errno = ECHILD;
  return -1;
}

// Удаление файла. Всегда ошибка «файл не найден».
int _unlink(char* name) {
  (void)name;
  errno = ENOENT;
  return -1;
}

// Времена процессора (CPU times). Не поддерживается — возвращаем -1.
clock_t _times(struct tms* buf) {
  (void)buf;
  return -1;
}

// Статус файла (по имени). Говорим «символьное устройство».
int _stat(const char* file, struct stat* st) {
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

// Создание ссылки на файл. Файловой системы нет — ошибка.
int _link(char* old, char* new) {
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

// Создание нового процесса (fork). ОС без процессов — ошибка.
int _fork(void) {
  errno = EAGAIN;
  return -1;
}

// Запуск другой программы (exec). Не поддерживается — ошибка.
int _execve(char* name, char** argv, char** env) {
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

// ----------------------------------------------------------------------------
// Доп. функции для компиляции (добавлены вручную для micro-ROS):
// библиотека rmw_microxrcedds вызывает их для таймаутов и «часов».
// ----------------------------------------------------------------------------

// Возвращает текущее «время» (момент с включения платы) в структуру timeval.
// tv_sec = секунды, tv_usec = микросекунды. HAL_GetTick() даёт миллисекунды.
int _gettimeofday(struct timeval* tv, void* tzvp) {
  (void)tzvp;
  // Возвращаем время с момента включения
  tv->tv_sec = HAL_GetTick() / 1000;
  tv->tv_usec = (HAL_GetTick() % 1000) * 1000;
  return 0;
}

// Задержка (sleep) на usec микросекунд. Через osDelay RTOS в миллисекундах.
int usleep(useconds_t usec) {
  uint32_t ms = usec / 1000;
  if (ms > 0) {
    osDelay(ms);
  }
  return 0;
}

// --- Picolibc Specific Section ---
#if defined(__PICOLIBC__)

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE* file) {
  (void)file;
  __io_putchar(c);
  return c;
}

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE* file) {
  unsigned char c;
  (void)file;
  c = __io_getchar();
  return c;
}

// Define and initialize the standard I/O streams for Picolibc.
// FDEV_SETUP_STREAM connects the starm_putc and starm_getc helper functions to
// a FILE structure. _FDEV_SETUP_RW indicates the stream is for reading and
// writing.
static FILE __stdio =
    FDEV_SETUP_STREAM(starm_putc, starm_getc, NULL, _FDEV_SETUP_RW);

// Assign the standard stream pointers (stdin, stdout, stderr) to the
// initialized stream. Picolibc uses these pointers for standard I/O operations
// (printf, scanf, etc.).
FILE* const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

// Create strong aliases mapping standard C library function names (without
// underscore) to the implemented system call stubs (with underscore). Picolibc
// uses these standard names internally, so this linking is required.
__strong_reference(_read, read);
__strong_reference(_write, write);
__strong_reference(_times, times);
__strong_reference(_execve, execve);
__strong_reference(_fork, fork);
__strong_reference(_link, link);
__strong_reference(_unlink, unlink);
__strong_reference(_stat, stat);
__strong_reference(_wait, wait);
__strong_reference(_open, open);
__strong_reference(_close, close);
__strong_reference(_lseek, lseek);
__strong_reference(_isatty, isatty);
__strong_reference(_fstat, fstat);
__strong_reference(_exit, exit);
__strong_reference(_kill, kill);
__strong_reference(_getpid, getpid);

#endif  //__PICOLIBC__
